site_name: BABEL

theme:
  name: material
  palette:
       # 深色模式配色
    - scheme: slate
      primary: deep-purple
      accent: teal
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式
features:
  - navigation.tabs  
  - toc.follow       

extra:
  generator: false  # 隐藏底部的生成器信息

copyright: "Copyright © 2025" 

nav:
  - '': index.md  # 关键：空字符串表示首页，不在导航栏显示
  - 第0章-梦呓: 
    - 第一章: 第0章-梦呓/1-梦魇.md
    - 第二章: 第0章-梦呓/2-晨曦.md
    - 第三章: 第0章-梦呓/3-午时.md
    - 第四章: 第0章-梦呓/4-夜火.md
    - 第五章: 第0章-梦呓/5-梦呓.md