site_name: BABEL

theme:
  name: material
  palette:
       # 深色模式配色
    - scheme: slate
      primary: deep-purple
      accent: teal
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式
features:
  - navigation.tabs  
  - toc.follow       

extra:
  generator: false  # 隐藏底部的生成器信息

copyright: "Copyright Moore. Lord of Babel © 2025" 

nav:
  - '': index.md  # 关键：空字符串表示首页，不在导航栏显示
  - 第0章-梦呓: 
    - 1-梦魇: 第0章-梦呓/1-梦魇.md
    - 2-晨曦: 第0章-梦呓/2-晨曦.md
    - 3-午时: 第0章-梦呓/3-午时.md
    - 4-夜火: 第0章-梦呓/4-夜火.md
    - 5-梦呓: 第0章-梦呓/5-梦呓.md
    - 6梦呓-惟耶利娅: 第0章-梦呓/6梦呓-惟耶利娅.md
    - 7梦呓-老村长: 第0章-梦呓/7梦呓-老村长.md
    - 8-归还: 第0章-梦呓/8-归还.md
    - 9-圣枪: 第0章-梦呓/9-圣枪.md
    - 10-剑鬼: 第0章-梦呓/10-剑鬼.md
    - 11-昏昭: 第0章-梦呓/11-昏昭.md
    - 12-时序: 第0章-梦呓/12-时序.md
    - 13-怪物: 第0章-梦呓/13-怪物.md